### ISSUE TITLE
Grammatical Change Suggestion - Allowing User to Record

### ISSUE THREAD

**Issue by PulwerJR** [selenium-webdriver-book/manuscript#13]
Grammatical Change Suggestion - Allowing User to Record

OLD:  "_Selenium IDE is a graphic interface allowing user to record a browser navigation session, which can be replayed afterward._"  

NEW:  "_Selenium IDE is a graphic interface allowing **users** to record a browser navigation session, which can be replayed afterward._"

**Comment by alexec** [comment]
Thank you! Wow, lots of comments - brilliant. We'll take a look and fix this on the next version!

**Comment by PulwerJR** [comment]
CLOSING: Duplicate
