### ISSUE TITLE
Lovely Reading Through Page 12

### ISSUE THREAD

**Issue by PulwerJR** [selenium-webdriver-book/manuscript#15]
I was really enjoying the book through page 12. I think it is well written and brimming with valuable content and obviously written by technically expert people. However (and maybe it's just me) I started to feel a bit adrift at sea when I started the JDK portion and didn't know where or how to get to the "$" prompt. I think this is a UNIX command prompt? I'm using Windows 7 Enterprise with Service Pack 1. My Command line prompt is "C:\>". Sorry for my ignorance, but, how do I get to the "$" prompt to run the JAVAC command to find which version of JDK is installed?

**Comment by alexec** [comment]
Hi, this should be the same process on Windows. Please try these instructions: https://www.windows-commandline.com/javac-not-recognized-internal-external-command/
