### ISSUE TITLE
Sorry - This is a "Real Nit" 

### ISSUE THREAD

**Issue by PulwerJR** [selenium-webdriver-book/manuscript#22]
OLD:  _CSS3 And HTML Unit Driver_

NEW:  _CSS3 **and** HTML Unit Driver_

**Comment by alexec** [comment]
Hi PluwerJR,

Just a thought, you could make these changes directly to the manuscript if you like by forking it. I'm sure myself and @yujunliang could give you credit in the book.

Alex

**Comment by PulwerJR** [comment]
Sir Alex,

What I’m currently doing is Highlighting the manuscript text that I see possibly needing a slight change, then putting a COMMENT in the Pop-up as to what I’m humbly suggesting.

By “Forking” what are the specific instructions to accomplish that, complete with an example, if you please.

I’m certain that “Credit” somewhere in the book, perhaps the “FOREWARD”, or some such spot, would win you a friend for life.

Kind Regards,
John Pulwers

**Comment by PulwerJR** [comment]
I know, put it in the Acknowledgement section as, " And Last, but at Least: Thanks to John Pulwers for his 'Forking Changes'."  No, really, I do not have Edit Capability with the Manuscript. Let me know if highlighting it with pop-up Comments will suffice.

**Comment by alexec** [comment]
As it sounds like the forking is not something you know well lets shelve that idea. We'll defiantly thank you for you comment, fork or no fork.

**Comment by yujunliang** [comment]
Forking is a technique when working on github, it allows you to have a copy of the code. Then you can submit your changes, and we can easily modify our transcripts using your changes.

Regards
Yujun
? AWS Fully Certified Professional

On Dec 21, 2016, at 8:36 AM, Alex Collins <notifications@github.com<mailto:notifications@github.com>> wrote:


As it sounds like the forking is not something you know well lets shelve that idea. We'll defiantly thank you for you comment, fork or no fork.

-

**Comment by PulwerJR** [comment]
OK, I’d certainly be willing to do that, especially if it will save you all time and effort. I’m looking it up now on “WhatIs.com”.

**Comment by PulwerJR** [comment]
I’m going to try this. I’ll just consider this a free lesson in collaboration, internationally.
