### ISSUE TITLE
Issues starting the server e.g. "mvn jetty:run" the error message says address is already in use

### ISSUE THREAD

**Issue by wshah88** [selenium-webdriver-book/manuscript#27]
Hi,

I am just starting the book and I am stuck already! I have maven installed but when I try to execute the command "mvn jetty:run" it is giving me an error of "Address is already in use: bind" Here is a snippet from the stack trace:

[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.3.7.v20160115:run (default-cli) on project selenium-webdriver-book: Failure: Address already in use: bind -> [Help 1]

I have attached the full strack trace. Can anyone help me with this error?
[stack trace full.txt](https://github.com/selenium-webdriver-book/manuscript/files/691780/stack.trace.full.txt)

**Comment by yujunliang** [comment]
You already have another tomcat running. Please stop that tomcat then run this again.

Regards
Yujun
? AWS Fully Certified Professional

On Jan 7, 2017, at 5:24 PM, wshah88 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am just starting the book and I am stuck already! I have maven installed but when I try to execute the command "mvn jetty:run" it is giving me an error of "Address is already in use: bind" Here is a snippet from the stack trace:

[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.3.7.v20160115:run (default-cli) on project selenium-webdriver-book: Failure: Address already in use: bind -> [Help 1]

I have attached the full strack trace. Can anyone help me with this error?
stack trace full.txt<https://github.com/selenium-webdriver-book/manuscript/files/691780/stack.trace.full.txt>

-

**Comment by wshah88** [comment]
Hi,

How do I do that? (Sorry still learning this stuff)

Is there any way to check the tomcats?

**Comment by yujunliang** [comment]
Did you install Jenkins or any other server?

Regards
Yujun
? AWS Fully Certified Professional

On Jan 7, 2017, at 5:30 PM, wshah88 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

How do I do that? (Sorry still learning this stuff)

Is there any way to check the tomcats?

-

**Comment by wshah88** [comment]
Hi,

Yes i installed jenkins the other week, i have just checked localhost:8080 and Jenkins is up and running. How do i stop this? is there any way i can use the selenium source project to use a different port so i can have both running?

**Comment by wshah88** [comment]
I have managed to stop Jenkins and i have run mvn jetty:run again and it seems to work however I am getting a lot of "Ignoring command with incorrect key" messages. The command has still not finished

**Comment by yujunliang** [comment]
Please run mvn verify.



Regards

Yujun

? AWS Fully Certified Professional



________________________________

**Comment by wshah88** [comment]
I did however there were some errors hat caused the build to fail.

Tests run: 226, Failures: 0, Errors: 6, Skipped: 23
See the txt file for full message: 
[mvn verify.txt](https://github.com/selenium-webdriver-book/manuscript/files/691812/mvn.verify.txt)

**Comment by yujunliang** [comment]
Ok.


I will check, but you can run "mvn jetty:run" now.


Regards

Yujun

? AWS Fully Certified Professional



________________________________

**Comment by wshah88** [comment]
I did but the "ignoring command with incorrect key" message was continuously printing to the command prompt, i had to cancel it via ctrl + c

**Comment by yujunliang** [comment]
can you copy everything?



Regards

Yujun

? AWS Fully Certified Professional



________________________________

**Comment by wshah88** [comment]
I am not sure what you mean? I have ran the commands as per instructions from the manual but kept getting that looping message, after i dont ctrl + c i went on the hello webdriver page that was working.

**Comment by yujunliang** [comment]
Can you try to reboot your PC?


Can you copy the messages from mvn jetty:run until ^C?




Regards

Yujun

? AWS Fully Certified Professional



________________________________

**Comment by wshah88** [comment]
Sure will try it again but will have to be tomorrow (currently 1:46am uk time) I'll continue with the project tomorrow if thats ok.

W

**Comment by yujunliang** [comment]
OK


http://stackoverflow.com/questions/31313642/ignoring-command-with-incorrect-key-message-in-console-from-jetty

[https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded]<http://stackoverflow.com/questions/31313642/ignoring-command-with-incorrect-key-message-in-console-from-jetty>

java - "Ignoring command with incorrect key" message in ...<http://stackoverflow.com/questions/31313642/ignoring-command-with-incorrect-key-message-in-console-from-jetty>
stackoverflow.com
After starting the jetty-server on my localhost and leaving it idle for about half hour I repeatedly get the message "Ignoring command with incorrect key".






Regards

Yujun

? AWS Fully Certified Professional



________________________________

**Comment by wshah88** [comment]
Ok i have ran that but it is still saying the ignore commend with incorrect key and is looping, only way to stop is to do ctrl c. I have attached the messages just before the ignore loop was happening
[mvn jetty command.txt](https://github.com/selenium-webdriver-book/manuscript/files/692107/mvn.jetty.command.txt)

**Comment by wshah88** [comment]
ok so i have read the links you sent and i have now changed the stopport from 9999 to 9966 and now i am not getting the ignore key message loop

**Comment by wshah88** [comment]
So i have now run mvn verify but there are still the 6 errors:

Results :

Tests in error:
swb.ch01intro.HelloWebDriverIT.helloWebDriver(swb.ch01intro.HelloWebDriverIT)
  Run 1: HelloWebDriverIT.setUp:20 » IllegalState The driver executable does not exist:...
  Run 2: HelloWebDriverIT.tearDown:25 NullPointer

  InjectedDriverIT.loadIndexPage » IllegalState Failed to load ApplicationContex...
  FirefoxDriverBinarySupplierIT.acquireFirefox:11 » Zip Not in GZIP format
  BackToFutureUsingJsDatepickIT.backToFuture1:30 » NullPointer
  BackToFutureUsingJsDatepickIT.backToFuture2:38 » NullPointer
  BackToFutureUsingJsDatepickIT.backToFuture3:46 » NullPointer

Tests run: 226, Failures: 0, Errors: 6, Skipped: 23

[INFO]
[INFO] --- jetty-maven-plugin:9.3.7.v20160115:stop (stop) @ selenium-webdriver-book ---
[INFO]
[INFO] --- maven-failsafe-plugin:2.18.1:verify (default) @ selenium-webdriver-book ---
[INFO] Failsafe report directory: C:\Users\wasim\source\target\failsafe-reports
[INFO] Stopped ServerConnector@c9b5a99{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] Stopped ServerConnector@23b1aa9{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:51 min
[INFO] Finished at: 2017-01-08T13:31:45+00:00
[INFO] Final Memory: 34M/353M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:verify (default) on project selenium-webdriver-book: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\wasim\source\target\failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by yujunliang** [comment]
Please ignore those tests for now. They failed after upgrading to Selenium 3.



Regards

Yujun

? AWS Fully Certified Professional



________________________________

**Comment by wshah88** [comment]
Ok no worries. Thanks for your help.

Closing this issue.
