### ISSUE TITLE
Automated Testing should be referred to as Automated Checking

### ISSUE THREAD

**Issue by dao-wolf** [selenium-webdriver-book/manuscript#32]
I appreciate the hard work that has gone into this book, but I would urge you to switch to using automated checking instead of automated testing or when referring to testing and automation. This book is going to be read by many who are new to this field and will be confused by the concept and definition of what testing is. It's our duty to educate correctly, unless of course you disagree with me.

**Comment by PulwerJR** [comment]
Mr. Wolf,

In my humblest of opinions, I must suggest that the term “Automated Checking” sounds much like a banking function related to EFT or EDI. If we can’t use the term “Testing”, may we call it “Automated Software Verification”?

**Comment by dao-wolf** [comment]
I think that “Automated Software Verification” is miles better than "Automated Testing".

**Comment by rownwe** [comment]
Isn't the title 

> Selenium WebDriver: From Foundations To Framework

telling enough?

**Comment by dao-wolf** [comment]
@rownwe i'm not sure what you're saying, could you please elaborate?
