### ISSUE TITLE
Example of driving WYSIWYG editor switches between bold and italics

### ISSUE THREAD

**Issue by davebachmann** [selenium-webdriver-book/manuscript#34]
In chapter 3, part of the example (figure 3) for entering text into a WYSIWYG editor shows entering text in bold, but the code in https://github.com/selenium-webdriver-book/source/blob/master/src/test/java/swb/ch03interacting/WyswygInputIT.java is selecting italics, and step 6 says to click the bold button, while step 8 says to type the italic text and step 10 says to deselect italics.

**Comment by alexec** [comment]
Need to look into this.

**Comment by davebachmann** [comment]
Thanks, Alex.  I'm enjoying reading the book.

I think you probably would just need to update the png with a screenshot showing italic typing, and update step 6 to say click the italics button.
