### ISSUE TITLE
Browser/driver text mismatch 

### ISSUE THREAD

**Issue by entropicrune** [selenium-webdriver-book/manuscript#4]
On page 17 of the leanpub PDF:
"1.  You can choose a different browser, e.t. selenium-**firefox**-driver is for the **Chrome** browser."

**Comment by yujunliang** [comment]
Thank you. Will change

Regards
Yujun
(347) 949 8586

On Nov 27, 2016, at 11:48 AM, entropicrune <notifications@github.com<mailto:notifications@github.com>> wrote:


On page 17 of the leanpub PDF:

??? ????????????????????????????????????????????????????????????????????????????? ???????????"1. You can choose a different browser, e.t. selenium-firefox-driver is for the Chrome browser."

-

**Comment by yujunliang** [comment]
Fixed.
