### ISSUE TITLE
Need for remote web driver?

### ISSUE THREAD

**Issue by entropicrune** [selenium-webdriver-book/manuscript#6]
Some sources say that if you want code on computer A to drive a web browser on computer B, you need to install a selenium server on B, and a remote client driver on A.  This seems to be on top of the WebDriver (like chromedriver) that's already on A.  Examples of this are [1, 2].

That seems silly, because you've already got a JSON API listening on A.  Why can't B communicate directly with that JSON API?  Does chromedriver support a different API than selenium server?  Furthermore your book (page 15 of the leanpub PDF) says "1. Create a new WebDriver, backed by either a local or remote browser."   

For whatever it's worth, I'm wanting computer B to be a regular, physical computer, and A to be a headless VM that's running (via Vagrant) as a guest on B.  I don't need a fancy grid.

I'm still confused!   A more detailed version of the diagram on page 9 would help.

[1] Thread at:  https://groups.google.com/forum/#!topic/selenium-users/4-0DmTSwxzg
[2] https://seleniumhq.github.io/docs/remote.html#remote_webdriver

**Comment by alexec** [comment]
Hi,

The reason that you need to run the standalone server, is that it is the server that starts-up the browser. I bet you could start the browser directly, but as soon as you call `driver.quit()` it would be closed and you'd need to manually start up another browser.

Alex

**Comment by alexec** [comment]
See appendix A to learn more about Selenium Grid.

**Comment by Edko24** [comment]
I have successfully install Maven on my system. I can type  mvn jetty:run  and mvn verify on  command prompt,but i cannot access the http://localhost:8080/hello-webdriver.html.How can i access  this test website



Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.



**mvn jetty:run**

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Tina>mvn jetty:run
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 10.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 6.7 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.688 s
[INFO] Finished at: 2016-12-06T19:50:48+00:00
[INFO] Final Memory: 12M/109M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'jetty' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Tina\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**http://localhost:8080/hello-webdriver.html**
This site can’t be reached

localhost refused to connect.
Search Google for localhost 8080 hello webdriver


**C:\Users\Tina>mvn verify**
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.122 s
[INFO] Finished at: 2016-12-06T19:54:59+00:00
[INFO] Final Memory: 5M/75M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\Tina). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException


Very frustrating that, for 3 days i cannot move from chapter One

Kindly see above my commsn prompt results.May be i am doing the wrong way

Ed
