### ISSUE TITLE
How to launch the test site

### ISSUE THREAD

**Issue by ghost** [selenium-webdriver-book/manuscript#7]
I have successfully install Maven on my system. I can type mvn jetty:run and mvn verify on command prompt,but i cannot access the http://localhost:8080/hello-webdriver.html.How can i access this test website

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

mvn jetty:run

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Tina>mvn jetty:run
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 10.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 6.7 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.688 s
[INFO] Finished at: 2016-12-06T19:50:48+00:00
[INFO] Final Memory: 12M/109M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'jetty' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Tina.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

http://localhost:8080/hello-webdriver.html
This site can’t be reached

localhost refused to connect.
Search Google for localhost 8080 hello webdriver

C:\Users\Tina>mvn verify
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.122 s
[INFO] Finished at: 2016-12-06T19:54:59+00:00
[INFO] Final Memory: 5M/75M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\Tina). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

Very frustrating that, for 3 days i cannot move from chapter One

Kindly see above my commsn prompt results.May be i am doing the wrong way

Ed

**Comment by alexec** [comment]
Hi,

From the error message, you are not in the correct directory. Once you've checked out the code, change into the directory. E.g. `cd source`.

Alex

**Comment by ghost** [comment]
Cool , worked fine

**Comment by PulwerJR** [comment]
Will someone be able to do the work if they don't want to use MAVEN? In other words, can they get by and still enjoy the fruits of the book using Gradle and Bamboo?

**Comment by alexec** [comment]
Updated README.md to indicate how to get application.
