### ISSUE TITLE
Army of QAs Manually Test

### ISSUE THREAD

**Issue by PulwerJR** [selenium-webdriver-book/manuscript#8]
OLD:  _Historically, the only way to mitigate this was to have army of QAs manually test on a variety of different configurations, a time-consuming and costly process_

NEW: _Historically, the only way to mitigate this was to have **an** army of QAs manually test on a variety of different configurations, a time-consuming and costly process_

**Comment by yujunliang** [comment]
Thank you.

Please keep coming with feedbacks.

We incorporate this into future changes to improve the book.

Regards
Yujun
(347) 949 8586

On Dec 14, 2016, at 2:18 PM, PulwerJR <notifications@github.com<mailto:notifications@github.com>> wrote:


Small grammatical suggestion to improve readability: This sentence "Historically, the only way to mitigate this was to have army of QAs manually test on a variety of different configurations, a time-consuming and costly process.", I thought it read better if written as "Historically, the only way to mitigate this was to have an army of QAs manually test on a variety of different configurations, a time-consuming and costly process.". No big deal, just my humble opinion.

-
